export { default as About } from './About/About'
export { default as Camera } from './Camera/Camera'
export { default as CapturedPhoto } from './CapturedPhoto/CapturedPhoto'
export { default as ColorGrid } from './ColorGrid/ColorGrid'
export { default as HomeTitle } from './HomeTitle/HomeTitle'
export { default as HomeWavePic } from './HomeWavePic/HomeWavePic'
export { default as NavBar } from './NavBar/NavBar'
